[tool.poetry]
name = "gopappy"
version = "1.7.1"
description = "GoDaddy v1 API implementation with secured auth token."
authors = [
    "Gamaliel Espinoza <gamaliel.espinoza@gmail.com>",
    "pythoninthegrass <4097471+pythoninthegrass@users.noreply.github.com>"
]
packages = [{ include = "gopappy", from = "src" }]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
gopappy = "gopappy.cli:app"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
colorama = "^0.4.6"
keyring = "^24.3.1"
keyrings-alt = "^5.0.2"
pycryptodome = "^3.19.1"
python-decouple = "^3.8"
requests = "^2.31.0"
typer = "^0.9.0"
wheel = "^0.43.0"

[tool.poetry.group.dev.dependencies]
icecream = "^2.1.3"
ipython = "^8.22.2"
poetry-plugin-export = "^1.6.0"
poetry-plugin-up = "^0.7.1"
rich = "^13.7.1"
ruff = "^0.2.1"

[tool.poetry.group.test.dependencies]
coverage = "^7.4.3"
hypothesis = {extras = ["cli"], version = "^6.98.17"}
pytest = "^7.4.4"
pytest-asyncio = "^0.21.1"
pytest-cov = "^4.1.0"
pytest-datafiles = "^3.0.0"
pytest-mock = "^3.14.0"
pytest-xdist = "^3.5.0"

[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
ignore = []
# Skip unused variable rules
extend-ignore = ["D203", "E203", "E251", "E266", "E401", "E402", "E501", "F401", "F403"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    "dist",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    "__pycache__",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Black (default: 88)
line-length = 130

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11.
target-version = "py311"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
